filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log
  tags: ["nginx-access"]

volumes:
  - ./nginx/logs:/var/log/nginx

output.kafka:
  hosts: ["kafka:9092"]
  topic: "nginx-logs"
  partition.round_robin:
    reachable_only: false
  required_acks: 1

logging.level: debug
